version: '3'

services:
  app:
    environment:
      - APP_SETTINGS=config.ProductionConfig
      - FLASK_APP=application/__init__.py

    build:
     context: .
     dockerfile: Dockerfile
#    ports:
#      - "5000:5000"




  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - app