FROM python:3.6-slim
RUN echo 'Dockerfile-App'
RUN mkdir /app
WORKDIR /app
COPY . /app
RUN pip install -U pip
RUN pip install --no-cache-dir -r requirements.txt
EXPOSE 5000
ENTRYPOINT flask run --host=0.0.0.0
