version: '3'

services:
  app_prod:
    environment:
      - APP_SETTINGS=config.ProductionConfig
      - FLASK_APP=application/__init__.py
      - DATABASE_URL=postgresql://lviv_pt:admin@postgres:5432/lviv_pt_db
      - REDIS_URL=redis://redis:6379
      - CELERY_BROKER_URL=redis://redis:6379
      - CELERY_RESULT_BACKEND=redis://redis:6379

    build:
     context: .
     dockerfile: Dockerfile

    depends_on:
      - postgres
      - celery
      - redis
      - publisher


  app_dev:
    environment:
      - APP_SETTINGS=config.DevelopmentConfig
      - FLASK_APP=application/__init__.py
      - DATABASE_URL=postgresql://lviv_pt:admin@postgres:5432/lviv_pt_db
      - REDIS_URL=redis://redis:6379
      - CELERY_BROKER_URL=redis://redis:6379
      - CELERY_RESULT_BACKEND=redis://redis:6379

    build:
     context: .
     dockerfile: Dockerfile-dev

    ports:
      - "5000:5000"

    depends_on:
      - postgres
      - celery
      - redis
      - publisher


  postgres:
    image: 'postgres:alpine'
    environment:
      - POSTGRES_USER=lviv_pt
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=lviv_pt_db
    ports:
      - "5432:5432"


  celery:
    environment:
      - APP_SETTINGS=config.ProductionConfig
      - REDIS_URL=redis://redis:6379
      - DATABASE_URL=postgresql://lviv_pt:admin@postgres:5432/lviv_pt_db

    build:
      context: .
      dockerfile: Dockerfile-celery

  redis:
    image: 'redis:alpine'


  publisher:
    environment:
      - APP_SETTINGS=config.ProductionConfig
      - REDIS_URL=redis://redis:6379
      - DATABASE_URL=postgresql://lviv_pt:admin@postgres:5432/lviv_pt_db

    build:
      context: .
      dockerfile: Dockerfile-beat


  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - app_prod