"""empty message

Revision ID: 1a8bb3810c59
Revises: 
Create Date: 2018-05-11 13:46:48.233923

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a8bb3810c59'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stops',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('internal_id', sa.String(), nullable=True),
    sa.Column('name', sa.Unicode(), nullable=True),
    sa.Column('code', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stops')
    # ### end Alembic commands ###
