"""empty message

Revision ID: 3bfc6e0e9f48
Revises: 
Create Date: 2018-05-24 11:51:03.300661

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3bfc6e0e9f48'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stops',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('internal_id', sa.String(), nullable=True),
    sa.Column('name', sa.Unicode(), nullable=True),
    sa.Column('code', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stops')
    # ### end Alembic commands ###
